### ISSUE TITLE
Adding correct version number to install packages

### ISSUE THREAD

**Issue by russellcameronthomas** [russellcameronthomas/MultiLab#3]
Right now, Ant is using "1.0" as a version number.  We need to fix this so that builds match the v-number that we enter for the github release (e.g. "v0.1").

**Comment by woodrad** [comment]
The pom still needs some touching up, but once it is set to automate the build, it will append the right version number.

**Comment by woodrad** [comment]
Maven will add the version number to the artifacts for you. Resolved!
