### ISSUE TITLE
Uploaded JAR file isn't running properly

### ISSUE THREAD

**Issue by russellcameronthomas** [russellcameronthomas/MultiLab#4]
My local version of the JAR file runs fine, but when I upload to the GitHub release and then download, it doesn't run.  Says it can't find the main class SimpleConsumptionWithUI.  I don't know why or how this is happening.

**Comment by russellcameronthomas** [comment]
I should add that the PKG version runs properly after installation.  I assume the same is true DMG.

**Comment by woodrad** [comment]
We should be able to package the jars with Maven now. I will add documentation on how to do this and we can start adding releases when you feel like the API is stable. Closing issue for now.
