### ISSUE TITLE
Migrate build to Maven

### ISSUE THREAD

**Issue by woodrad** [russellcameronthomas/MultiLab#6]
We need to set up the build to use the Maven standard directory structure and complete work on the pom so we can have a build automated with Maven.

**Comment by woodrad** [comment]
@russellcameronthomas: what name would you like to use for the package? To get an idea of what you might use, check the [docs](http://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html). Maybe something like edu.gmu.[deptname].multilab?

**Comment by russellcameronthomas** [comment]
I think this works: "edu.gmu.css.multilab".  The department is "Computational Social Science", an there is no other project like "multilab" that I know of.

**Comment by woodrad** [comment]
Resolved in #7
